[build]
  command = "npm i -gs yarn && yarn build"
  publish = "public"
[[redirects]]
from = "/discord"
to = "https://discord.gg/p4FzcwX"
status = 301
force = true
[[redirects]]
from = "/spotify"
to = "https://open.spotify.com/playlist/09m47es0Nh028Sogw3rQvS?si=fHV52jDEQd6iJHAgjIOLTw"
status = 301
force = true
[[redirects]]
from = "/market"
to = "https://docs.google.com/spreadsheets/d/1U5a7bMPuVRVEDjxOQML_Oq_q1GBsDQXWFBu01kD6zpg"
status = 301
force = true
[[redirects]]
from = "/price-check-guide"
to = "https://docs.google.com/spreadsheets/d/13arzuRizakKuCCyFsuSD9w4F48v8Yj48ZTL_fPrsuTI"
status = 301
force = true
[[redirects]]
from = "/lending-ledger"
to = "https://docs.google.com/spreadsheets/d/10A5aUBZlVZUHnIy8yDxqpb9kzDyrNUBuCwGtFsOoHFI"
status = 301
force = true
